#include "ps.h"
#include "ps_evdev.h"
#include "util/ps_text.h"
#include <linux/input.h>

/* Represent KEY or BTN event.
 */

static const char *ps_evdev_btnid_KEY_repr(int code) {
  switch (code) {
    case KEY_ESC: return "KEY_ESC";
    case KEY_1: return "KEY_1";
    case KEY_2: return "KEY_2";
    case KEY_3: return "KEY_3";
    case KEY_4: return "KEY_4";
    case KEY_5: return "KEY_5";
    case KEY_6: return "KEY_6";
    case KEY_7: return "KEY_7";
    case KEY_8: return "KEY_8";
    case KEY_9: return "KEY_9";
    case KEY_0: return "KEY_0";
    case KEY_MINUS: return "KEY_MINUS";
    case KEY_EQUAL: return "KEY_EQUAL";
    case KEY_BACKSPACE: return "KEY_BACKSPACE";
    case KEY_TAB: return "KEY_TAB";
    case KEY_Q: return "KEY_Q";
    case KEY_W: return "KEY_W";
    case KEY_E: return "KEY_E";
    case KEY_R: return "KEY_R";
    case KEY_T: return "KEY_T";
    case KEY_Y: return "KEY_Y";
    case KEY_U: return "KEY_U";
    case KEY_I: return "KEY_I";
    case KEY_O: return "KEY_O";
    case KEY_P: return "KEY_P";
    case KEY_LEFTBRACE: return "KEY_LEFTBRACE";
    case KEY_RIGHTBRACE: return "KEY_RIGHTBRACE";
    case KEY_ENTER: return "KEY_ENTER";
    case KEY_LEFTCTRL: return "KEY_LEFTCTRL";
    case KEY_A: return "KEY_A";
    case KEY_S: return "KEY_S";
    case KEY_D: return "KEY_D";
    case KEY_F: return "KEY_F";
    case KEY_G: return "KEY_G";
    case KEY_H: return "KEY_H";
    case KEY_J: return "KEY_J";
    case KEY_K: return "KEY_K";
    case KEY_L: return "KEY_L";
    case KEY_SEMICOLON: return "KEY_SEMICOLON";
    case KEY_APOSTROPHE: return "KEY_APOSTROPHE";
    case KEY_GRAVE: return "KEY_GRAVE";
    case KEY_LEFTSHIFT: return "KEY_LEFTSHIFT";
    case KEY_BACKSLASH: return "KEY_BACKSLASH";
    case KEY_Z: return "KEY_Z";
    case KEY_X: return "KEY_X";
    case KEY_C: return "KEY_C";
    case KEY_V: return "KEY_V";
    case KEY_B: return "KEY_B";
    case KEY_N: return "KEY_N";
    case KEY_M: return "KEY_M";
    case KEY_COMMA: return "KEY_COMMA";
    case KEY_DOT: return "KEY_DOT";
    case KEY_SLASH: return "KEY_SLASH";
    case KEY_RIGHTSHIFT: return "KEY_RIGHTSHIFT";
    case KEY_KPASTERISK: return "KEY_KPASTERISK";
    case KEY_LEFTALT: return "KEY_LEFTALT";
    case KEY_SPACE: return "KEY_SPACE";
    case KEY_CAPSLOCK: return "KEY_CAPSLOCK";
    case KEY_F1: return "KEY_F1";
    case KEY_F2: return "KEY_F2";
    case KEY_F3: return "KEY_F3";
    case KEY_F4: return "KEY_F4";
    case KEY_F5: return "KEY_F5";
    case KEY_F6: return "KEY_F6";
    case KEY_F7: return "KEY_F7";
    case KEY_F8: return "KEY_F8";
    case KEY_F9: return "KEY_F9";
    case KEY_F10: return "KEY_F10";
    case KEY_NUMLOCK: return "KEY_NUMLOCK";
    case KEY_SCROLLLOCK: return "KEY_SCROLLLOCK";
    case KEY_KP7: return "KEY_KP7";
    case KEY_KP8: return "KEY_KP8";
    case KEY_KP9: return "KEY_KP9";
    case KEY_KPMINUS: return "KEY_KPMINUS";
    case KEY_KP4: return "KEY_KP4";
    case KEY_KP5: return "KEY_KP5";
    case KEY_KP6: return "KEY_KP6";
    case KEY_KPPLUS: return "KEY_KPPLUS";
    case KEY_KP1: return "KEY_KP1";
    case KEY_KP2: return "KEY_KP2";
    case KEY_KP3: return "KEY_KP3";
    case KEY_KP0: return "KEY_KP0";
    case KEY_KPDOT: return "KEY_KPDOT";
    case KEY_ZENKAKUHANKAKU: return "KEY_ZENKAKUHANKAKU";
    case KEY_102ND: return "KEY_102ND";
    case KEY_F11: return "KEY_F11";
    case KEY_F12: return "KEY_F12";
    case KEY_RO: return "KEY_RO";
    case KEY_KATAKANA: return "KEY_KATAKANA";
    case KEY_HIRAGANA: return "KEY_HIRAGANA";
    case KEY_HENKAN: return "KEY_HENKAN";
    case KEY_KATAKANAHIRAGANA: return "KEY_KATAKANAHIRAGANA";
    case KEY_MUHENKAN: return "KEY_MUHENKAN";
    case KEY_KPJPCOMMA: return "KEY_KPJPCOMMA";
    case KEY_KPENTER: return "KEY_KPENTER";
    case KEY_RIGHTCTRL: return "KEY_RIGHTCTRL";
    case KEY_KPSLASH: return "KEY_KPSLASH";
    case KEY_SYSRQ: return "KEY_SYSRQ";
    case KEY_RIGHTALT: return "KEY_RIGHTALT";
    case KEY_LINEFEED: return "KEY_LINEFEED";
    case KEY_HOME: return "KEY_HOME";
    case KEY_UP: return "KEY_UP";
    case KEY_PAGEUP: return "KEY_PAGEUP";
    case KEY_LEFT: return "KEY_LEFT";
    case KEY_RIGHT: return "KEY_RIGHT";
    case KEY_END: return "KEY_END";
    case KEY_DOWN: return "KEY_DOWN";
    case KEY_PAGEDOWN: return "KEY_PAGEDOWN";
    case KEY_INSERT: return "KEY_INSERT";
    case KEY_DELETE: return "KEY_DELETE";
    case KEY_MACRO: return "KEY_MACRO";
    case KEY_MUTE: return "KEY_MUTE";
    case KEY_VOLUMEDOWN: return "KEY_VOLUMEDOWN";
    case KEY_VOLUMEUP: return "KEY_VOLUMEUP";
    case KEY_KPEQUAL: return "KEY_KPEQUAL";
    case KEY_KPPLUSMINUS: return "KEY_KPPLUSMINUS";
    case KEY_PAUSE: return "KEY_PAUSE";
    case KEY_KPCOMMA: return "KEY_KPCOMMA";
    case KEY_HANGEUL: return "KEY_HANGEUL";
    case KEY_HANJA: return "KEY_HANJA";
    case KEY_YEN: return "KEY_YEN";
    case KEY_LEFTMETA: return "KEY_LEFTMETA";
    case KEY_RIGHTMETA: return "KEY_RIGHTMETA";
    case KEY_COMPOSE: return "KEY_COMPOSE";
    case KEY_AGAIN: return "KEY_AGAIN";
    case KEY_FRONT: return "KEY_FRONT";
    case KEY_SETUP: return "KEY_SETUP";
    case KEY_SENDFILE: return "KEY_SENDFILE";
    case KEY_DELETEFILE: return "KEY_DELETEFILE";
    case KEY_XFER: return "KEY_XFER";
    case KEY_PROG1: return "KEY_PROG1";
    case KEY_PROG2: return "KEY_PROG2";
    case KEY_MSDOS: return "KEY_MSDOS";
    case KEY_SCREENLOCK: return "KEY_SCREENLOCK";
    case KEY_DIRECTION: return "KEY_DIRECTION";
    case KEY_CYCLEWINDOWS: return "KEY_CYCLEWINDOWS";
    case KEY_MAIL: return "KEY_MAIL";
    case KEY_COMPUTER: return "KEY_COMPUTER";
    case KEY_CLOSECD: return "KEY_CLOSECD";
    case KEY_EJECTCD: return "KEY_EJECTCD";
    case KEY_EJECTCLOSECD: return "KEY_EJECTCLOSECD";
    case KEY_NEXTSONG: return "KEY_NEXTSONG";
    case KEY_PLAYPAUSE: return "KEY_PLAYPAUSE";
    case KEY_PREVIOUSSONG: return "KEY_PREVIOUSSONG";
    case KEY_STOPCD: return "KEY_STOPCD";
    case KEY_RECORD: return "KEY_RECORD";
    case KEY_REWIND: return "KEY_REWIND";
    case KEY_ISO: return "KEY_ISO";
    case KEY_MOVE: return "KEY_MOVE";
    case KEY_EDIT: return "KEY_EDIT";
    case KEY_SCROLLUP: return "KEY_SCROLLUP";
    case KEY_SCROLLDOWN: return "KEY_SCROLLDOWN";
    case KEY_KPLEFTPAREN: return "KEY_KPLEFTPAREN";
    case KEY_KPRIGHTPAREN: return "KEY_KPRIGHTPAREN";
    case KEY_F13: return "KEY_F13";
    case KEY_F14: return "KEY_F14";
    case KEY_F15: return "KEY_F15";
    case KEY_F16: return "KEY_F16";
    case KEY_F17: return "KEY_F17";
    case KEY_F18: return "KEY_F18";
    case KEY_F19: return "KEY_F19";
    case KEY_F20: return "KEY_F20";
    case KEY_F21: return "KEY_F21";
    case KEY_F22: return "KEY_F22";
    case KEY_F23: return "KEY_F23";
    case KEY_F24: return "KEY_F24";
    case KEY_PLAYCD: return "KEY_PLAYCD";
    case KEY_PAUSECD: return "KEY_PAUSECD";
    case KEY_PROG3: return "KEY_PROG3";
    case KEY_PROG4: return "KEY_PROG4";
    case KEY_SUSPEND: return "KEY_SUSPEND";
    case KEY_PLAY: return "KEY_PLAY";
    case KEY_FASTFORWARD: return "KEY_FASTFORWARD";
    case KEY_BASSBOOST: return "KEY_BASSBOOST";
    case KEY_HP: return "KEY_HP";
    case KEY_CAMERA: return "KEY_CAMERA";
    case KEY_SOUND: return "KEY_SOUND";
    case KEY_QUESTION: return "KEY_QUESTION";
    case KEY_EMAIL: return "KEY_EMAIL";
    case KEY_CHAT: return "KEY_CHAT";
    case KEY_SEARCH: return "KEY_SEARCH";
    case KEY_CONNECT: return "KEY_CONNECT";
    case KEY_SPORT: return "KEY_SPORT";
    case KEY_SHOP: return "KEY_SHOP";
    case KEY_ALTERASE: return "KEY_ALTERASE";
    case KEY_BRIGHTNESSDOWN: return "KEY_BRIGHTNESSDOWN";
    case KEY_BRIGHTNESSUP: return "KEY_BRIGHTNESSUP";
    case KEY_MEDIA: return "KEY_MEDIA";
    case KEY_KBDILLUMTOGGLE: return "KEY_KBDILLUMTOGGLE";
    case KEY_KBDILLUMDOWN: return "KEY_KBDILLUMDOWN";
    case KEY_KBDILLUMUP: return "KEY_KBDILLUMUP";
    case KEY_DOCUMENTS: return "KEY_DOCUMENTS";
    case KEY_BATTERY: return "KEY_BATTERY";
    case KEY_BLUETOOTH: return "KEY_BLUETOOTH";
    case KEY_WLAN: return "KEY_WLAN";
    case KEY_UWB: return "KEY_UWB";
    case KEY_UNKNOWN: return "KEY_UNKNOWN";
    case KEY_BRIGHTNESS_ZERO: return "KEY_BRIGHTNESS_ZERO";
    case KEY_WIMAX: return "KEY_WIMAX";
    case KEY_OK: return "KEY_OK";
    case KEY_SELECT: return "KEY_SELECT";
    case KEY_GOTO: return "KEY_GOTO";
    case KEY_CLEAR: return "KEY_CLEAR";
    case KEY_POWER2: return "KEY_POWER2";
    case KEY_OPTION: return "KEY_OPTION";
    case KEY_TIME: return "KEY_TIME";
    case KEY_VENDOR: return "KEY_VENDOR";
    case KEY_ARCHIVE: return "KEY_ARCHIVE";
    case KEY_CHANNEL: return "KEY_CHANNEL";
    case KEY_FAVORITES: return "KEY_FAVORITES";
    case KEY_EPG: return "KEY_EPG";
    case KEY_MHP: return "KEY_MHP";
    case KEY_LANGUAGE: return "KEY_LANGUAGE";
    case KEY_TITLE: return "KEY_TITLE";
    case KEY_SUBTITLE: return "KEY_SUBTITLE";
    case KEY_ANGLE: return "KEY_ANGLE";
    case KEY_ZOOM: return "KEY_ZOOM";
    case KEY_MODE: return "KEY_MODE";
    case KEY_KEYBOARD: return "KEY_KEYBOARD";
    case KEY_SCREEN: return "KEY_SCREEN";
    case KEY_SAT2: return "KEY_SAT2";
    case KEY_RADIO: return "KEY_RADIO";
    case KEY_PLAYER: return "KEY_PLAYER";
    case KEY_TEXT: return "KEY_TEXT";
    case KEY_AUX: return "KEY_AUX";
    case KEY_MP3: return "KEY_MP3";
    case KEY_DIRECTORY: return "KEY_DIRECTORY";
    case KEY_LIST: return "KEY_LIST";
    case KEY_CALENDAR: return "KEY_CALENDAR";
    case KEY_RED: return "KEY_RED";
    case KEY_GREEN: return "KEY_GREEN";
    case KEY_YELLOW: return "KEY_YELLOW";
    case KEY_BLUE: return "KEY_BLUE";
    case KEY_FIRST: return "KEY_FIRST";
    case KEY_AB: return "KEY_AB";
    case KEY_NEXT: return "KEY_NEXT";
    case KEY_RESTART: return "KEY_RESTART";
    case KEY_SLOW: return "KEY_SLOW";
    case KEY_SHUFFLE: return "KEY_SHUFFLE";
    case KEY_BREAK: return "KEY_BREAK";
    case KEY_PREVIOUS: return "KEY_PREVIOUS";
    case KEY_DIGITS: return "KEY_DIGITS";
    case KEY_TEEN: return "KEY_TEEN";
    case KEY_TWEN: return "KEY_TWEN";
    case KEY_BRIGHTNESS_TOGGLE: return "KEY_BRIGHTNESS_TOGGLE";
    case KEY_DOLLAR: return "KEY_DOLLAR";
    case KEY_EURO: return "KEY_EURO";
    case KEY_FRAMEFORWARD: return "KEY_FRAMEFORWARD";
    case KEY_DEL_EOL: return "KEY_DEL_EOL";
    case KEY_DEL_EOS: return "KEY_DEL_EOS";
    case KEY_INS_LINE: return "KEY_INS_LINE";
    case KEY_DEL_LINE: return "KEY_DEL_LINE";
    case KEY_FN: return "KEY_FN";
    case KEY_FN_ESC: return "KEY_FN_ESC";
    case KEY_FN_F1: return "KEY_FN_F1";
    case KEY_FN_F2: return "KEY_FN_F2";
    case KEY_FN_F3: return "KEY_FN_F3";
    case KEY_FN_F4: return "KEY_FN_F4";
    case KEY_FN_F5: return "KEY_FN_F5";
    case KEY_FN_F6: return "KEY_FN_F6";
    case KEY_FN_F7: return "KEY_FN_F7";
    case KEY_FN_F8: return "KEY_FN_F8";
    case KEY_FN_F9: return "KEY_FN_F9";
    case KEY_FN_F10: return "KEY_FN_F10";
    case KEY_FN_F11: return "KEY_FN_F11";
    case KEY_FN_F12: return "KEY_FN_F12";
    case KEY_FN_1: return "KEY_FN_1";
    case KEY_FN_2: return "KEY_FN_2";
    case KEY_FN_D: return "KEY_FN_D";
    case KEY_FN_E: return "KEY_FN_E";
    case KEY_FN_F: return "KEY_FN_F";
    case KEY_FN_S: return "KEY_FN_S";
    case KEY_FN_B: return "KEY_FN_B";
    case KEY_BRL_DOT1: return "KEY_BRL_DOT1";
    case KEY_BRL_DOT2: return "KEY_BRL_DOT2";
    case KEY_BRL_DOT3: return "KEY_BRL_DOT3";
    case KEY_BRL_DOT4: return "KEY_BRL_DOT4";
    case KEY_BRL_DOT5: return "KEY_BRL_DOT5";
    case KEY_BRL_DOT6: return "KEY_BRL_DOT6";
    case KEY_BRL_DOT7: return "KEY_BRL_DOT7";
    case KEY_BRL_DOT8: return "KEY_BRL_DOT8";
    case KEY_BRL_DOT9: return "KEY_BRL_DOT9";
    case KEY_BRL_DOT10: return "KEY_BRL_DOT10";
    case KEY_NUMERIC_2: return "KEY_NUMERIC_2";
    case KEY_NUMERIC_3: return "KEY_NUMERIC_3";
    case KEY_NUMERIC_4: return "KEY_NUMERIC_4";
    case KEY_NUMERIC_5: return "KEY_NUMERIC_5";
    case KEY_NUMERIC_6: return "KEY_NUMERIC_6";
    case KEY_NUMERIC_7: return "KEY_NUMERIC_7";
    case KEY_NUMERIC_8: return "KEY_NUMERIC_8";
    case KEY_NUMERIC_9: return "KEY_NUMERIC_9";
    case KEY_NUMERIC_STAR: return "KEY_NUMERIC_STAR";
    case KEY_NUMERIC_POUND: return "KEY_NUMERIC_POUND";
    case KEY_CAMERA_FOCUS: return "KEY_CAMERA_FOCUS";
    case KEY_TOUCHPAD_ON: return "KEY_TOUCHPAD_ON";
    case KEY_TOUCHPAD_OFF: return "KEY_TOUCHPAD_OFF";
    case KEY_CAMERA_ZOOMIN: return "KEY_CAMERA_ZOOMIN";
    case KEY_CAMERA_ZOOMOUT: return "KEY_CAMERA_ZOOMOUT";
    case KEY_CAMERA_UP: return "KEY_CAMERA_UP";
    case KEY_CAMERA_DOWN: return "KEY_CAMERA_DOWN";
    case KEY_CAMERA_LEFT: return "KEY_CAMERA_LEFT";
    case KEY_CAMERA_RIGHT: return "KEY_CAMERA_RIGHT";
    case KEY_ATTENDANT_ON: return "KEY_ATTENDANT_ON";
    case KEY_ATTENDANT_OFF: return "KEY_ATTENDANT_OFF";
    case KEY_KBDINPUTASSIST_PREV: return "KEY_KBDINPUTASSIST_PREV";
    case KEY_KBDINPUTASSIST_NEXT: return "KEY_KBDINPUTASSIST_NEXT";
    case KEY_KBDINPUTASSIST_PREVGROUP: return "KEY_KBDINPUTASSIST_PREVGROUP";
    case KEY_KBDINPUTASSIST_NEXTGROUP: return "KEY_KBDINPUTASSIST_NEXTGROUP";
    case KEY_KBDINPUTASSIST_ACCEPT: return "KEY_KBDINPUTASSIST_ACCEPT";
    case KEY_KBDINPUTASSIST_CANCEL: return "KEY_KBDINPUTASSIST_CANCEL";
    case BTN_0: return "BTN_0";
    case BTN_1: return "BTN_1";
    case BTN_2: return "BTN_2";
    case BTN_3: return "BTN_3";
    case BTN_4: return "BTN_4";
    case BTN_5: return "BTN_5";
    case BTN_6: return "BTN_6";
    case BTN_7: return "BTN_7";
    case BTN_8: return "BTN_8";
    case BTN_9: return "BTN_9";
    case BTN_LEFT: return "BTN_LEFT";
    case BTN_RIGHT: return "BTN_RIGHT";
    case BTN_MIDDLE: return "BTN_MIDDLE";
    case BTN_SIDE: return "BTN_SIDE";
    case BTN_EXTRA: return "BTN_EXTRA";
    case BTN_FORWARD: return "BTN_FORWARD";
    case BTN_BACK: return "BTN_BACK";
    case BTN_TASK: return "BTN_TASK";
    case BTN_TRIGGER: return "BTN_TRIGGER";
    case BTN_THUMB: return "BTN_THUMB";
    case BTN_THUMB2: return "BTN_THUMB2";
    case BTN_TOP: return "BTN_TOP";
    case BTN_TOP2: return "BTN_TOP2";
    case BTN_PINKIE: return "BTN_PINKIE";
    case BTN_BASE: return "BTN_BASE";
    case BTN_BASE2: return "BTN_BASE2";
    case BTN_BASE3: return "BTN_BASE3";
    case BTN_BASE4: return "BTN_BASE4";
    case BTN_BASE5: return "BTN_BASE5";
    case BTN_BASE6: return "BTN_BASE6";
    case BTN_DEAD: return "BTN_DEAD";
    case BTN_A: return "BTN_A";
    case BTN_B: return "BTN_B";
    case BTN_C: return "BTN_C";
    case BTN_X: return "BTN_X";
    case BTN_Y: return "BTN_Y";
    case BTN_Z: return "BTN_Z";
    case BTN_TL: return "BTN_TL";
    case BTN_TR: return "BTN_TR";
    case BTN_TL2: return "BTN_TL2";
    case BTN_TR2: return "BTN_TR2";
    case BTN_SELECT: return "BTN_SELECT";
    case BTN_START: return "BTN_START";
    case BTN_MODE: return "BTN_MODE";
    case BTN_THUMBL: return "BTN_THUMBL";
    case BTN_THUMBR: return "BTN_THUMBR";
    case BTN_TOOL_PEN: return "BTN_TOOL_PEN";
    case BTN_TOOL_RUBBER: return "BTN_TOOL_RUBBER";
    case BTN_TOOL_BRUSH: return "BTN_TOOL_BRUSH";
    case BTN_TOOL_PENCIL: return "BTN_TOOL_PENCIL";
    case BTN_TOOL_AIRBRUSH: return "BTN_TOOL_AIRBRUSH";
    case BTN_TOOL_FINGER: return "BTN_TOOL_FINGER";
    case BTN_TOOL_MOUSE: return "BTN_TOOL_MOUSE";
    case BTN_TOOL_LENS: return "BTN_TOOL_LENS";
    case BTN_TOUCH: return "BTN_TOUCH";
    case BTN_STYLUS: return "BTN_STYLUS";
    case BTN_STYLUS2: return "BTN_STYLUS2";
    case BTN_TOOL_DOUBLETAP: return "BTN_TOOL_DOUBLETAP";
    case BTN_TOOL_TRIPLETAP: return "BTN_TOOL_TRIPLETAP";
    case BTN_GEAR_DOWN: return "BTN_GEAR_DOWN";
    case BTN_GEAR_UP: return "BTN_GEAR_UP";
    case BTN_DPAD_UP: return "BTN_DPAD_UP";
    case BTN_DPAD_DOWN: return "BTN_DPAD_DOWN";
    case BTN_DPAD_LEFT: return "BTN_DPAD_LEFT";
    case BTN_DPAD_RIGHT: return "BTN_DPAD_RIGHT";
    case BTN_TRIGGER_HAPPY1: return "BTN_TRIGGER_HAPPY1";
    case BTN_TRIGGER_HAPPY2: return "BTN_TRIGGER_HAPPY2";
    case BTN_TRIGGER_HAPPY3: return "BTN_TRIGGER_HAPPY3";
    case BTN_TRIGGER_HAPPY4: return "BTN_TRIGGER_HAPPY4";
    case BTN_TRIGGER_HAPPY5: return "BTN_TRIGGER_HAPPY5";
    case BTN_TRIGGER_HAPPY6: return "BTN_TRIGGER_HAPPY6";
    case BTN_TRIGGER_HAPPY7: return "BTN_TRIGGER_HAPPY7";
    case BTN_TRIGGER_HAPPY8: return "BTN_TRIGGER_HAPPY8";
    case BTN_TRIGGER_HAPPY9: return "BTN_TRIGGER_HAPPY9";
    case BTN_TRIGGER_HAPPY10: return "BTN_TRIGGER_HAPPY10";
    case BTN_TRIGGER_HAPPY11: return "BTN_TRIGGER_HAPPY11";
    case BTN_TRIGGER_HAPPY12: return "BTN_TRIGGER_HAPPY12";
    case BTN_TRIGGER_HAPPY13: return "BTN_TRIGGER_HAPPY13";
    case BTN_TRIGGER_HAPPY14: return "BTN_TRIGGER_HAPPY14";
    case BTN_TRIGGER_HAPPY15: return "BTN_TRIGGER_HAPPY15";
    case BTN_TRIGGER_HAPPY16: return "BTN_TRIGGER_HAPPY16";
    case BTN_TRIGGER_HAPPY17: return "BTN_TRIGGER_HAPPY17";
    case BTN_TRIGGER_HAPPY18: return "BTN_TRIGGER_HAPPY18";
    case BTN_TRIGGER_HAPPY19: return "BTN_TRIGGER_HAPPY19";
    case BTN_TRIGGER_HAPPY20: return "BTN_TRIGGER_HAPPY20";
    case BTN_TRIGGER_HAPPY21: return "BTN_TRIGGER_HAPPY21";
    case BTN_TRIGGER_HAPPY22: return "BTN_TRIGGER_HAPPY22";
    case BTN_TRIGGER_HAPPY23: return "BTN_TRIGGER_HAPPY23";
    case BTN_TRIGGER_HAPPY24: return "BTN_TRIGGER_HAPPY24";
    case BTN_TRIGGER_HAPPY25: return "BTN_TRIGGER_HAPPY25";
    case BTN_TRIGGER_HAPPY26: return "BTN_TRIGGER_HAPPY26";
    case BTN_TRIGGER_HAPPY27: return "BTN_TRIGGER_HAPPY27";
    case BTN_TRIGGER_HAPPY28: return "BTN_TRIGGER_HAPPY28";
    case BTN_TRIGGER_HAPPY29: return "BTN_TRIGGER_HAPPY29";
    case BTN_TRIGGER_HAPPY30: return "BTN_TRIGGER_HAPPY30";
    case BTN_TRIGGER_HAPPY31: return "BTN_TRIGGER_HAPPY31";
    case BTN_TRIGGER_HAPPY32: return "BTN_TRIGGER_HAPPY32";
    case BTN_TRIGGER_HAPPY33: return "BTN_TRIGGER_HAPPY33";
    case BTN_TRIGGER_HAPPY34: return "BTN_TRIGGER_HAPPY34";
    case BTN_TRIGGER_HAPPY35: return "BTN_TRIGGER_HAPPY35";
    case BTN_TRIGGER_HAPPY36: return "BTN_TRIGGER_HAPPY36";
    case BTN_TRIGGER_HAPPY37: return "BTN_TRIGGER_HAPPY37";
    case BTN_TRIGGER_HAPPY38: return "BTN_TRIGGER_HAPPY38";
    case BTN_TRIGGER_HAPPY39: return "BTN_TRIGGER_HAPPY39";
    case BTN_TRIGGER_HAPPY40: return "BTN_TRIGGER_HAPPY40";
  }
  return 0;
}

/* Represent ABS event.
 */

static const char *ps_evdev_btnid_ABS_repr(int code) {
  switch (code) {
    case ABS_X: return "ABS_X";
    case ABS_Y: return "ABS_Y";
    case ABS_Z: return "ABS_Z";
    case ABS_RX: return "ABS_RX";
    case ABS_RY: return "ABS_RY";
    case ABS_RZ: return "ABS_RZ";
    case ABS_THROTTLE: return "ABS_THROTTLE";
    case ABS_RUDDER: return "ABS_RUDDER";
    case ABS_WHEEL: return "ABS_WHEEL";
    case ABS_GAS: return "ABS_GAS";
    case ABS_BRAKE: return "ABS_BRAKE";
    case ABS_HAT0X: return "ABS_HAT0X";
    case ABS_HAT0Y: return "ABS_HAT0Y";
    case ABS_HAT1X: return "ABS_HAT1X";
    case ABS_HAT1Y: return "ABS_HAT1Y";
    case ABS_HAT2X: return "ABS_HAT2X";
    case ABS_HAT2Y: return "ABS_HAT2Y";
    case ABS_HAT3X: return "ABS_HAT3X";
    case ABS_HAT3Y: return "ABS_HAT3Y";
    case ABS_PRESSURE: return "ABS_PRESSURE";
    case ABS_DISTANCE: return "ABS_DISTANCE";
    case ABS_TILT_X: return "ABS_TILT_X";
    case ABS_TILT_Y: return "ABS_TILT_Y";
    case ABS_TOOL_WIDTH: return "ABS_TOOL_WIDTH";
    case ABS_VOLUME: return "ABS_VOLUME";
    case ABS_MISC: return "ABS_MISC";
  }
  return 0;
}

/* Represent REL event.
 */

static const char *ps_evdev_btnid_REL_repr(int code) {
  switch (code) {
    case REL_X: return "REL_X";
    case REL_Y: return "REL_Y";
    case REL_Z: return "REL_Z";
    case REL_RX: return "REL_RX";
    case REL_RY: return "REL_RY";
    case REL_RZ: return "REL_RZ";
    case REL_HWHEEL: return "REL_HWHEEL";
    case REL_DIAL: return "REL_DIAL";
    case REL_WHEEL: return "REL_WHEEL";
    case REL_MISC: return "REL_MISC";
  }
  return 0;
}

/* Represent button.
 */
 
int ps_evdev_btnid_repr(char *dst,int dsta,int btnid) {
  if (!dst||(dsta<0)) dsta=0;
  int type=btnid>>16;
  int code=(btnid&0xffff);
  const char *name=0;
  switch (type) {
    case EV_KEY: name=ps_evdev_btnid_KEY_repr(code); break;
    case EV_ABS: name=ps_evdev_btnid_ABS_repr(code); break;
    case EV_REL: name=ps_evdev_btnid_REL_repr(code); break;
  }
  if (!name||!name[0]) return -1;
  int namec=0; while (name[namec]) namec++;
  if (namec<=dsta) {
    memcpy(dst,name,namec);
    if (namec<dsta) dst[namec]=0;
  }
  return namec;
}

/* Evaluate KEY event, without prefix.
 */

static int ps_evdev_btnid_KEY_eval(const char *src,int srcc) {
  if ((srcc==8)&&!(ps_memcasecmp(src,"RESERVED",srcc))) return 0;
  if ((srcc==3)&&!(ps_memcasecmp(src,"ESC",srcc))) return 1;
  if ((srcc==1)&&!(ps_memcasecmp(src,"1",srcc))) return 2;
  if ((srcc==1)&&!(ps_memcasecmp(src,"2",srcc))) return 3;
  if ((srcc==1)&&!(ps_memcasecmp(src,"3",srcc))) return 4;
  if ((srcc==1)&&!(ps_memcasecmp(src,"4",srcc))) return 5;
  if ((srcc==1)&&!(ps_memcasecmp(src,"5",srcc))) return 6;
  if ((srcc==1)&&!(ps_memcasecmp(src,"6",srcc))) return 7;
  if ((srcc==1)&&!(ps_memcasecmp(src,"7",srcc))) return 8;
  if ((srcc==1)&&!(ps_memcasecmp(src,"8",srcc))) return 9;
  if ((srcc==1)&&!(ps_memcasecmp(src,"9",srcc))) return 10;
  if ((srcc==1)&&!(ps_memcasecmp(src,"0",srcc))) return 11;
  if ((srcc==5)&&!(ps_memcasecmp(src,"MINUS",srcc))) return 12;
  if ((srcc==5)&&!(ps_memcasecmp(src,"EQUAL",srcc))) return 13;
  if ((srcc==9)&&!(ps_memcasecmp(src,"BACKSPACE",srcc))) return 14;
  if ((srcc==3)&&!(ps_memcasecmp(src,"TAB",srcc))) return 15;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Q",srcc))) return 16;
  if ((srcc==1)&&!(ps_memcasecmp(src,"W",srcc))) return 17;
  if ((srcc==1)&&!(ps_memcasecmp(src,"E",srcc))) return 18;
  if ((srcc==1)&&!(ps_memcasecmp(src,"R",srcc))) return 19;
  if ((srcc==1)&&!(ps_memcasecmp(src,"T",srcc))) return 20;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Y",srcc))) return 21;
  if ((srcc==1)&&!(ps_memcasecmp(src,"U",srcc))) return 22;
  if ((srcc==1)&&!(ps_memcasecmp(src,"I",srcc))) return 23;
  if ((srcc==1)&&!(ps_memcasecmp(src,"O",srcc))) return 24;
  if ((srcc==1)&&!(ps_memcasecmp(src,"P",srcc))) return 25;
  if ((srcc==9)&&!(ps_memcasecmp(src,"LEFTBRACE",srcc))) return 26;
  if ((srcc==10)&&!(ps_memcasecmp(src,"RIGHTBRACE",srcc))) return 27;
  if ((srcc==5)&&!(ps_memcasecmp(src,"ENTER",srcc))) return 28;
  if ((srcc==8)&&!(ps_memcasecmp(src,"LEFTCTRL",srcc))) return 29;
  if ((srcc==1)&&!(ps_memcasecmp(src,"A",srcc))) return 30;
  if ((srcc==1)&&!(ps_memcasecmp(src,"S",srcc))) return 31;
  if ((srcc==1)&&!(ps_memcasecmp(src,"D",srcc))) return 32;
  if ((srcc==1)&&!(ps_memcasecmp(src,"F",srcc))) return 33;
  if ((srcc==1)&&!(ps_memcasecmp(src,"G",srcc))) return 34;
  if ((srcc==1)&&!(ps_memcasecmp(src,"H",srcc))) return 35;
  if ((srcc==1)&&!(ps_memcasecmp(src,"J",srcc))) return 36;
  if ((srcc==1)&&!(ps_memcasecmp(src,"K",srcc))) return 37;
  if ((srcc==1)&&!(ps_memcasecmp(src,"L",srcc))) return 38;
  if ((srcc==9)&&!(ps_memcasecmp(src,"SEMICOLON",srcc))) return 39;
  if ((srcc==10)&&!(ps_memcasecmp(src,"APOSTROPHE",srcc))) return 40;
  if ((srcc==5)&&!(ps_memcasecmp(src,"GRAVE",srcc))) return 41;
  if ((srcc==9)&&!(ps_memcasecmp(src,"LEFTSHIFT",srcc))) return 42;
  if ((srcc==9)&&!(ps_memcasecmp(src,"BACKSLASH",srcc))) return 43;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Z",srcc))) return 44;
  if ((srcc==1)&&!(ps_memcasecmp(src,"X",srcc))) return 45;
  if ((srcc==1)&&!(ps_memcasecmp(src,"C",srcc))) return 46;
  if ((srcc==1)&&!(ps_memcasecmp(src,"V",srcc))) return 47;
  if ((srcc==1)&&!(ps_memcasecmp(src,"B",srcc))) return 48;
  if ((srcc==1)&&!(ps_memcasecmp(src,"N",srcc))) return 49;
  if ((srcc==1)&&!(ps_memcasecmp(src,"M",srcc))) return 50;
  if ((srcc==5)&&!(ps_memcasecmp(src,"COMMA",srcc))) return 51;
  if ((srcc==3)&&!(ps_memcasecmp(src,"DOT",srcc))) return 52;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SLASH",srcc))) return 53;
  if ((srcc==10)&&!(ps_memcasecmp(src,"RIGHTSHIFT",srcc))) return 54;
  if ((srcc==10)&&!(ps_memcasecmp(src,"KPASTERISK",srcc))) return 55;
  if ((srcc==7)&&!(ps_memcasecmp(src,"LEFTALT",srcc))) return 56;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SPACE",srcc))) return 57;
  if ((srcc==8)&&!(ps_memcasecmp(src,"CAPSLOCK",srcc))) return 58;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F1",srcc))) return 59;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F2",srcc))) return 60;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F3",srcc))) return 61;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F4",srcc))) return 62;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F5",srcc))) return 63;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F6",srcc))) return 64;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F7",srcc))) return 65;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F8",srcc))) return 66;
  if ((srcc==2)&&!(ps_memcasecmp(src,"F9",srcc))) return 67;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F10",srcc))) return 68;
  if ((srcc==7)&&!(ps_memcasecmp(src,"NUMLOCK",srcc))) return 69;
  if ((srcc==10)&&!(ps_memcasecmp(src,"SCROLLLOCK",srcc))) return 70;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP7",srcc))) return 71;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP8",srcc))) return 72;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP9",srcc))) return 73;
  if ((srcc==7)&&!(ps_memcasecmp(src,"KPMINUS",srcc))) return 74;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP4",srcc))) return 75;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP5",srcc))) return 76;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP6",srcc))) return 77;
  if ((srcc==6)&&!(ps_memcasecmp(src,"KPPLUS",srcc))) return 78;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP1",srcc))) return 79;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP2",srcc))) return 80;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP3",srcc))) return 81;
  if ((srcc==3)&&!(ps_memcasecmp(src,"KP0",srcc))) return 82;
  if ((srcc==5)&&!(ps_memcasecmp(src,"KPDOT",srcc))) return 83;
  if ((srcc==14)&&!(ps_memcasecmp(src,"ZENKAKUHANKAKU",srcc))) return 85;
  if ((srcc==5)&&!(ps_memcasecmp(src,"102ND",srcc))) return 86;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F11",srcc))) return 87;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F12",srcc))) return 88;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RO",srcc))) return 89;
  if ((srcc==8)&&!(ps_memcasecmp(src,"KATAKANA",srcc))) return 90;
  if ((srcc==8)&&!(ps_memcasecmp(src,"HIRAGANA",srcc))) return 91;
  if ((srcc==6)&&!(ps_memcasecmp(src,"HENKAN",srcc))) return 92;
  if ((srcc==16)&&!(ps_memcasecmp(src,"KATAKANAHIRAGANA",srcc))) return 93;
  if ((srcc==8)&&!(ps_memcasecmp(src,"MUHENKAN",srcc))) return 94;
  if ((srcc==9)&&!(ps_memcasecmp(src,"KPJPCOMMA",srcc))) return 95;
  if ((srcc==7)&&!(ps_memcasecmp(src,"KPENTER",srcc))) return 96;
  if ((srcc==9)&&!(ps_memcasecmp(src,"RIGHTCTRL",srcc))) return 97;
  if ((srcc==7)&&!(ps_memcasecmp(src,"KPSLASH",srcc))) return 98;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SYSRQ",srcc))) return 99;
  if ((srcc==8)&&!(ps_memcasecmp(src,"RIGHTALT",srcc))) return 100;
  if ((srcc==8)&&!(ps_memcasecmp(src,"LINEFEED",srcc))) return 101;
  if ((srcc==4)&&!(ps_memcasecmp(src,"HOME",srcc))) return 102;
  if ((srcc==2)&&!(ps_memcasecmp(src,"UP",srcc))) return 103;
  if ((srcc==6)&&!(ps_memcasecmp(src,"PAGEUP",srcc))) return 104;
  if ((srcc==4)&&!(ps_memcasecmp(src,"LEFT",srcc))) return 105;
  if ((srcc==5)&&!(ps_memcasecmp(src,"RIGHT",srcc))) return 106;
  if ((srcc==3)&&!(ps_memcasecmp(src,"END",srcc))) return 107;
  if ((srcc==4)&&!(ps_memcasecmp(src,"DOWN",srcc))) return 108;
  if ((srcc==8)&&!(ps_memcasecmp(src,"PAGEDOWN",srcc))) return 109;
  if ((srcc==6)&&!(ps_memcasecmp(src,"INSERT",srcc))) return 110;
  if ((srcc==6)&&!(ps_memcasecmp(src,"DELETE",srcc))) return 111;
  if ((srcc==5)&&!(ps_memcasecmp(src,"MACRO",srcc))) return 112;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MUTE",srcc))) return 113;
  if ((srcc==10)&&!(ps_memcasecmp(src,"VOLUMEDOWN",srcc))) return 114;
  if ((srcc==8)&&!(ps_memcasecmp(src,"VOLUMEUP",srcc))) return 115;
  if ((srcc==7)&&!(ps_memcasecmp(src,"KPEQUAL",srcc))) return 117;
  if ((srcc==11)&&!(ps_memcasecmp(src,"KPPLUSMINUS",srcc))) return 118;
  if ((srcc==5)&&!(ps_memcasecmp(src,"PAUSE",srcc))) return 119;
  if ((srcc==7)&&!(ps_memcasecmp(src,"KPCOMMA",srcc))) return 121;
  if ((srcc==7)&&!(ps_memcasecmp(src,"HANGEUL",srcc))) return 122;
  if ((srcc==7)&&!(ps_memcasecmp(src,"HANGUEL",srcc))) return 122;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HANJA",srcc))) return 123;
  if ((srcc==3)&&!(ps_memcasecmp(src,"YEN",srcc))) return 124;
  if ((srcc==8)&&!(ps_memcasecmp(src,"LEFTMETA",srcc))) return 125;
  if ((srcc==9)&&!(ps_memcasecmp(src,"RIGHTMETA",srcc))) return 126;
  if ((srcc==7)&&!(ps_memcasecmp(src,"COMPOSE",srcc))) return 127;
  if ((srcc==5)&&!(ps_memcasecmp(src,"AGAIN",srcc))) return 129;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FRONT",srcc))) return 132;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SETUP",srcc))) return 141;
  if ((srcc==8)&&!(ps_memcasecmp(src,"SENDFILE",srcc))) return 145;
  if ((srcc==10)&&!(ps_memcasecmp(src,"DELETEFILE",srcc))) return 146;
  if ((srcc==4)&&!(ps_memcasecmp(src,"XFER",srcc))) return 147;
  if ((srcc==5)&&!(ps_memcasecmp(src,"PROG1",srcc))) return 148;
  if ((srcc==5)&&!(ps_memcasecmp(src,"PROG2",srcc))) return 149;
  if ((srcc==5)&&!(ps_memcasecmp(src,"MSDOS",srcc))) return 151;
  if ((srcc==10)&&!(ps_memcasecmp(src,"SCREENLOCK",srcc))) return KEY_COFFEE;
  if ((srcc==9)&&!(ps_memcasecmp(src,"DIRECTION",srcc))) return 153;
  if ((srcc==12)&&!(ps_memcasecmp(src,"CYCLEWINDOWS",srcc))) return 154;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MAIL",srcc))) return 155;
  if ((srcc==8)&&!(ps_memcasecmp(src,"COMPUTER",srcc))) return 157;
  if ((srcc==7)&&!(ps_memcasecmp(src,"CLOSECD",srcc))) return 160;
  if ((srcc==7)&&!(ps_memcasecmp(src,"EJECTCD",srcc))) return 161;
  if ((srcc==12)&&!(ps_memcasecmp(src,"EJECTCLOSECD",srcc))) return 162;
  if ((srcc==8)&&!(ps_memcasecmp(src,"NEXTSONG",srcc))) return 163;
  if ((srcc==9)&&!(ps_memcasecmp(src,"PLAYPAUSE",srcc))) return 164;
  if ((srcc==12)&&!(ps_memcasecmp(src,"PREVIOUSSONG",srcc))) return 165;
  if ((srcc==6)&&!(ps_memcasecmp(src,"STOPCD",srcc))) return 166;
  if ((srcc==6)&&!(ps_memcasecmp(src,"RECORD",srcc))) return 167;
  if ((srcc==6)&&!(ps_memcasecmp(src,"REWIND",srcc))) return 168;
  if ((srcc==3)&&!(ps_memcasecmp(src,"ISO",srcc))) return 170;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MOVE",srcc))) return 175;
  if ((srcc==4)&&!(ps_memcasecmp(src,"EDIT",srcc))) return 176;
  if ((srcc==8)&&!(ps_memcasecmp(src,"SCROLLUP",srcc))) return 177;
  if ((srcc==10)&&!(ps_memcasecmp(src,"SCROLLDOWN",srcc))) return 178;
  if ((srcc==11)&&!(ps_memcasecmp(src,"KPLEFTPAREN",srcc))) return 179;
  if ((srcc==12)&&!(ps_memcasecmp(src,"KPRIGHTPAREN",srcc))) return 180;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F13",srcc))) return 183;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F14",srcc))) return 184;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F15",srcc))) return 185;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F16",srcc))) return 186;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F17",srcc))) return 187;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F18",srcc))) return 188;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F19",srcc))) return 189;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F20",srcc))) return 190;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F21",srcc))) return 191;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F22",srcc))) return 192;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F23",srcc))) return 193;
  if ((srcc==3)&&!(ps_memcasecmp(src,"F24",srcc))) return 194;
  if ((srcc==6)&&!(ps_memcasecmp(src,"PLAYCD",srcc))) return 200;
  if ((srcc==7)&&!(ps_memcasecmp(src,"PAUSECD",srcc))) return 201;
  if ((srcc==5)&&!(ps_memcasecmp(src,"PROG3",srcc))) return 202;
  if ((srcc==5)&&!(ps_memcasecmp(src,"PROG4",srcc))) return 203;
  if ((srcc==7)&&!(ps_memcasecmp(src,"SUSPEND",srcc))) return 205;
  if ((srcc==4)&&!(ps_memcasecmp(src,"PLAY",srcc))) return 207;
  if ((srcc==11)&&!(ps_memcasecmp(src,"FASTFORWARD",srcc))) return 208;
  if ((srcc==9)&&!(ps_memcasecmp(src,"BASSBOOST",srcc))) return 209;
  if ((srcc==2)&&!(ps_memcasecmp(src,"HP",srcc))) return 211;
  if ((srcc==6)&&!(ps_memcasecmp(src,"CAMERA",srcc))) return 212;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SOUND",srcc))) return 213;
  if ((srcc==8)&&!(ps_memcasecmp(src,"QUESTION",srcc))) return 214;
  if ((srcc==5)&&!(ps_memcasecmp(src,"EMAIL",srcc))) return 215;
  if ((srcc==4)&&!(ps_memcasecmp(src,"CHAT",srcc))) return 216;
  if ((srcc==6)&&!(ps_memcasecmp(src,"SEARCH",srcc))) return 217;
  if ((srcc==7)&&!(ps_memcasecmp(src,"CONNECT",srcc))) return 218;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SPORT",srcc))) return 220;
  if ((srcc==4)&&!(ps_memcasecmp(src,"SHOP",srcc))) return 221;
  if ((srcc==8)&&!(ps_memcasecmp(src,"ALTERASE",srcc))) return 222;
  if ((srcc==14)&&!(ps_memcasecmp(src,"BRIGHTNESSDOWN",srcc))) return 224;
  if ((srcc==12)&&!(ps_memcasecmp(src,"BRIGHTNESSUP",srcc))) return 225;
  if ((srcc==5)&&!(ps_memcasecmp(src,"MEDIA",srcc))) return 226;
  if ((srcc==14)&&!(ps_memcasecmp(src,"KBDILLUMTOGGLE",srcc))) return 228;
  if ((srcc==12)&&!(ps_memcasecmp(src,"KBDILLUMDOWN",srcc))) return 229;
  if ((srcc==10)&&!(ps_memcasecmp(src,"KBDILLUMUP",srcc))) return 230;
  if ((srcc==9)&&!(ps_memcasecmp(src,"DOCUMENTS",srcc))) return 235;
  if ((srcc==7)&&!(ps_memcasecmp(src,"BATTERY",srcc))) return 236;
  if ((srcc==9)&&!(ps_memcasecmp(src,"BLUETOOTH",srcc))) return 237;
  if ((srcc==4)&&!(ps_memcasecmp(src,"WLAN",srcc))) return 238;
  if ((srcc==3)&&!(ps_memcasecmp(src,"UWB",srcc))) return 239;
  if ((srcc==7)&&!(ps_memcasecmp(src,"UNKNOWN",srcc))) return 240;
  if ((srcc==15)&&!(ps_memcasecmp(src,"BRIGHTNESS_ZERO",srcc))) return KEY_BRIGHTNESS_AUTO;
  if ((srcc==5)&&!(ps_memcasecmp(src,"WIMAX",srcc))) return KEY_WWAN;
  if ((srcc==2)&&!(ps_memcasecmp(src,"OK",srcc))) return 0x160;
  if ((srcc==6)&&!(ps_memcasecmp(src,"SELECT",srcc))) return 0x161;
  if ((srcc==4)&&!(ps_memcasecmp(src,"GOTO",srcc))) return 0x162;
  if ((srcc==5)&&!(ps_memcasecmp(src,"CLEAR",srcc))) return 0x163;
  if ((srcc==6)&&!(ps_memcasecmp(src,"POWER2",srcc))) return 0x164;
  if ((srcc==6)&&!(ps_memcasecmp(src,"OPTION",srcc))) return 0x165;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TIME",srcc))) return 0x167;
  if ((srcc==6)&&!(ps_memcasecmp(src,"VENDOR",srcc))) return 0x168;
  if ((srcc==7)&&!(ps_memcasecmp(src,"ARCHIVE",srcc))) return 0x169;
  if ((srcc==7)&&!(ps_memcasecmp(src,"CHANNEL",srcc))) return 0x16b;
  if ((srcc==9)&&!(ps_memcasecmp(src,"FAVORITES",srcc))) return 0x16c;
  if ((srcc==3)&&!(ps_memcasecmp(src,"EPG",srcc))) return 0x16d;
  if ((srcc==3)&&!(ps_memcasecmp(src,"MHP",srcc))) return 0x16f;
  if ((srcc==8)&&!(ps_memcasecmp(src,"LANGUAGE",srcc))) return 0x170;
  if ((srcc==5)&&!(ps_memcasecmp(src,"TITLE",srcc))) return 0x171;
  if ((srcc==8)&&!(ps_memcasecmp(src,"SUBTITLE",srcc))) return 0x172;
  if ((srcc==5)&&!(ps_memcasecmp(src,"ANGLE",srcc))) return 0x173;
  if ((srcc==4)&&!(ps_memcasecmp(src,"ZOOM",srcc))) return 0x174;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MODE",srcc))) return 0x175;
  if ((srcc==8)&&!(ps_memcasecmp(src,"KEYBOARD",srcc))) return 0x176;
  if ((srcc==6)&&!(ps_memcasecmp(src,"SCREEN",srcc))) return 0x177;
  if ((srcc==4)&&!(ps_memcasecmp(src,"SAT2",srcc))) return 0x17e;
  if ((srcc==5)&&!(ps_memcasecmp(src,"RADIO",srcc))) return 0x181;
  if ((srcc==6)&&!(ps_memcasecmp(src,"PLAYER",srcc))) return 0x183;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TEXT",srcc))) return 0x184;
  if ((srcc==3)&&!(ps_memcasecmp(src,"AUX",srcc))) return 0x186;
  if ((srcc==3)&&!(ps_memcasecmp(src,"MP3",srcc))) return 0x187;
  if ((srcc==9)&&!(ps_memcasecmp(src,"DIRECTORY",srcc))) return 0x18a;
  if ((srcc==4)&&!(ps_memcasecmp(src,"LIST",srcc))) return 0x18b;
  if ((srcc==8)&&!(ps_memcasecmp(src,"CALENDAR",srcc))) return 0x18d;
  if ((srcc==3)&&!(ps_memcasecmp(src,"RED",srcc))) return 0x18e;
  if ((srcc==5)&&!(ps_memcasecmp(src,"GREEN",srcc))) return 0x18f;
  if ((srcc==6)&&!(ps_memcasecmp(src,"YELLOW",srcc))) return 0x190;
  if ((srcc==4)&&!(ps_memcasecmp(src,"BLUE",srcc))) return 0x191;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FIRST",srcc))) return 0x194;
  if ((srcc==2)&&!(ps_memcasecmp(src,"AB",srcc))) return 0x196;
  if ((srcc==4)&&!(ps_memcasecmp(src,"NEXT",srcc))) return 0x197;
  if ((srcc==7)&&!(ps_memcasecmp(src,"RESTART",srcc))) return 0x198;
  if ((srcc==4)&&!(ps_memcasecmp(src,"SLOW",srcc))) return 0x199;
  if ((srcc==7)&&!(ps_memcasecmp(src,"SHUFFLE",srcc))) return 0x19a;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BREAK",srcc))) return 0x19b;
  if ((srcc==8)&&!(ps_memcasecmp(src,"PREVIOUS",srcc))) return 0x19c;
  if ((srcc==6)&&!(ps_memcasecmp(src,"DIGITS",srcc))) return 0x19d;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TEEN",srcc))) return 0x19e;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TWEN",srcc))) return 0x19f;
  if ((srcc==17)&&!(ps_memcasecmp(src,"BRIGHTNESS_TOGGLE",srcc))) return KEY_DISPLAYTOGGLE;
  if ((srcc==6)&&!(ps_memcasecmp(src,"DOLLAR",srcc))) return 0x1b2;
  if ((srcc==4)&&!(ps_memcasecmp(src,"EURO",srcc))) return 0x1b3;
  if ((srcc==12)&&!(ps_memcasecmp(src,"FRAMEFORWARD",srcc))) return 0x1b5;
  if ((srcc==7)&&!(ps_memcasecmp(src,"DEL_EOL",srcc))) return 0x1c0;
  if ((srcc==7)&&!(ps_memcasecmp(src,"DEL_EOS",srcc))) return 0x1c1;
  if ((srcc==8)&&!(ps_memcasecmp(src,"INS_LINE",srcc))) return 0x1c2;
  if ((srcc==8)&&!(ps_memcasecmp(src,"DEL_LINE",srcc))) return 0x1c3;
  if ((srcc==2)&&!(ps_memcasecmp(src,"FN",srcc))) return 0x1d0;
  if ((srcc==6)&&!(ps_memcasecmp(src,"FN_ESC",srcc))) return 0x1d1;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F1",srcc))) return 0x1d2;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F2",srcc))) return 0x1d3;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F3",srcc))) return 0x1d4;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F4",srcc))) return 0x1d5;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F5",srcc))) return 0x1d6;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F6",srcc))) return 0x1d7;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F7",srcc))) return 0x1d8;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F8",srcc))) return 0x1d9;
  if ((srcc==5)&&!(ps_memcasecmp(src,"FN_F9",srcc))) return 0x1da;
  if ((srcc==6)&&!(ps_memcasecmp(src,"FN_F10",srcc))) return 0x1db;
  if ((srcc==6)&&!(ps_memcasecmp(src,"FN_F11",srcc))) return 0x1dc;
  if ((srcc==6)&&!(ps_memcasecmp(src,"FN_F12",srcc))) return 0x1dd;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_1",srcc))) return 0x1de;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_2",srcc))) return 0x1df;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_D",srcc))) return 0x1e0;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_E",srcc))) return 0x1e1;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_F",srcc))) return 0x1e2;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_S",srcc))) return 0x1e3;
  if ((srcc==4)&&!(ps_memcasecmp(src,"FN_B",srcc))) return 0x1e4;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT1",srcc))) return 0x1f1;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT2",srcc))) return 0x1f2;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT3",srcc))) return 0x1f3;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT4",srcc))) return 0x1f4;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT5",srcc))) return 0x1f5;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT6",srcc))) return 0x1f6;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT7",srcc))) return 0x1f7;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT8",srcc))) return 0x1f8;
  if ((srcc==8)&&!(ps_memcasecmp(src,"BRL_DOT9",srcc))) return 0x1f9;
  if ((srcc==9)&&!(ps_memcasecmp(src,"BRL_DOT10",srcc))) return 0x1fa;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_2",srcc))) return 0x202;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_3",srcc))) return 0x203;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_4",srcc))) return 0x204;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_5",srcc))) return 0x205;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_6",srcc))) return 0x206;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_7",srcc))) return 0x207;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_8",srcc))) return 0x208;
  if ((srcc==9)&&!(ps_memcasecmp(src,"NUMERIC_9",srcc))) return 0x209;
  if ((srcc==12)&&!(ps_memcasecmp(src,"NUMERIC_STAR",srcc))) return 0x20a;
  if ((srcc==13)&&!(ps_memcasecmp(src,"NUMERIC_POUND",srcc))) return 0x20b;
  if ((srcc==12)&&!(ps_memcasecmp(src,"CAMERA_FOCUS",srcc))) return 0x210;
  if ((srcc==11)&&!(ps_memcasecmp(src,"TOUCHPAD_ON",srcc))) return 0x213;
  if ((srcc==12)&&!(ps_memcasecmp(src,"TOUCHPAD_OFF",srcc))) return 0x214;
  if ((srcc==13)&&!(ps_memcasecmp(src,"CAMERA_ZOOMIN",srcc))) return 0x215;
  if ((srcc==14)&&!(ps_memcasecmp(src,"CAMERA_ZOOMOUT",srcc))) return 0x216;
  if ((srcc==9)&&!(ps_memcasecmp(src,"CAMERA_UP",srcc))) return 0x217;
  if ((srcc==11)&&!(ps_memcasecmp(src,"CAMERA_DOWN",srcc))) return 0x218;
  if ((srcc==11)&&!(ps_memcasecmp(src,"CAMERA_LEFT",srcc))) return 0x219;
  if ((srcc==12)&&!(ps_memcasecmp(src,"CAMERA_RIGHT",srcc))) return 0x21a;
  if ((srcc==12)&&!(ps_memcasecmp(src,"ATTENDANT_ON",srcc))) return 0x21b;
  if ((srcc==13)&&!(ps_memcasecmp(src,"ATTENDANT_OFF",srcc))) return 0x21c;
  if ((srcc==19)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_PREV",srcc))) return 0x260;
  if ((srcc==19)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_NEXT",srcc))) return 0x261;
  if ((srcc==24)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_PREVGROUP",srcc))) return 0x262;
  if ((srcc==24)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_NEXTGROUP",srcc))) return 0x263;
  if ((srcc==21)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_ACCEPT",srcc))) return 0x264;
  if ((srcc==21)&&!(ps_memcasecmp(src,"KBDINPUTASSIST_CANCEL",srcc))) return 0x265;
  if ((srcc==15)&&!(ps_memcasecmp(src,"MIN_INTERESTING",srcc))) return KEY_MUTE;
  return -1;
}

/* Evaluate BTN event, without prefix.
 */

static int ps_evdev_btnid_BTN_eval(const char *src,int srcc) {
  if ((srcc==4)&&!(ps_memcasecmp(src,"MISC",srcc))) return 0x100;
  if ((srcc==1)&&!(ps_memcasecmp(src,"0",srcc))) return 0x100;
  if ((srcc==1)&&!(ps_memcasecmp(src,"1",srcc))) return 0x101;
  if ((srcc==1)&&!(ps_memcasecmp(src,"2",srcc))) return 0x102;
  if ((srcc==1)&&!(ps_memcasecmp(src,"3",srcc))) return 0x103;
  if ((srcc==1)&&!(ps_memcasecmp(src,"4",srcc))) return 0x104;
  if ((srcc==1)&&!(ps_memcasecmp(src,"5",srcc))) return 0x105;
  if ((srcc==1)&&!(ps_memcasecmp(src,"6",srcc))) return 0x106;
  if ((srcc==1)&&!(ps_memcasecmp(src,"7",srcc))) return 0x107;
  if ((srcc==1)&&!(ps_memcasecmp(src,"8",srcc))) return 0x108;
  if ((srcc==1)&&!(ps_memcasecmp(src,"9",srcc))) return 0x109;
  if ((srcc==5)&&!(ps_memcasecmp(src,"MOUSE",srcc))) return 0x110;
  if ((srcc==4)&&!(ps_memcasecmp(src,"LEFT",srcc))) return 0x110;
  if ((srcc==5)&&!(ps_memcasecmp(src,"RIGHT",srcc))) return 0x111;
  if ((srcc==6)&&!(ps_memcasecmp(src,"MIDDLE",srcc))) return 0x112;
  if ((srcc==4)&&!(ps_memcasecmp(src,"SIDE",srcc))) return 0x113;
  if ((srcc==5)&&!(ps_memcasecmp(src,"EXTRA",srcc))) return 0x114;
  if ((srcc==7)&&!(ps_memcasecmp(src,"FORWARD",srcc))) return 0x115;
  if ((srcc==4)&&!(ps_memcasecmp(src,"BACK",srcc))) return 0x116;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TASK",srcc))) return 0x117;
  if ((srcc==8)&&!(ps_memcasecmp(src,"JOYSTICK",srcc))) return 0x120;
  if ((srcc==7)&&!(ps_memcasecmp(src,"TRIGGER",srcc))) return 0x120;
  if ((srcc==5)&&!(ps_memcasecmp(src,"THUMB",srcc))) return 0x121;
  if ((srcc==6)&&!(ps_memcasecmp(src,"THUMB2",srcc))) return 0x122;
  if ((srcc==3)&&!(ps_memcasecmp(src,"TOP",srcc))) return 0x123;
  if ((srcc==4)&&!(ps_memcasecmp(src,"TOP2",srcc))) return 0x124;
  if ((srcc==6)&&!(ps_memcasecmp(src,"PINKIE",srcc))) return 0x125;
  if ((srcc==4)&&!(ps_memcasecmp(src,"BASE",srcc))) return 0x126;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BASE2",srcc))) return 0x127;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BASE3",srcc))) return 0x128;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BASE4",srcc))) return 0x129;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BASE5",srcc))) return 0x12a;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BASE6",srcc))) return 0x12b;
  if ((srcc==4)&&!(ps_memcasecmp(src,"DEAD",srcc))) return 0x12f;
  if ((srcc==7)&&!(ps_memcasecmp(src,"GAMEPAD",srcc))) return 0x130;
  if ((srcc==5)&&!(ps_memcasecmp(src,"SOUTH",srcc))) return 0x130;
  if ((srcc==1)&&!(ps_memcasecmp(src,"A",srcc))) return BTN_SOUTH;
  if ((srcc==4)&&!(ps_memcasecmp(src,"EAST",srcc))) return 0x131;
  if ((srcc==1)&&!(ps_memcasecmp(src,"B",srcc))) return BTN_EAST;
  if ((srcc==1)&&!(ps_memcasecmp(src,"C",srcc))) return 0x132;
  if ((srcc==5)&&!(ps_memcasecmp(src,"NORTH",srcc))) return 0x133;
  if ((srcc==1)&&!(ps_memcasecmp(src,"X",srcc))) return BTN_NORTH;
  if ((srcc==4)&&!(ps_memcasecmp(src,"WEST",srcc))) return 0x134;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Y",srcc))) return BTN_WEST;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Z",srcc))) return 0x135;
  if ((srcc==2)&&!(ps_memcasecmp(src,"TL",srcc))) return 0x136;
  if ((srcc==2)&&!(ps_memcasecmp(src,"TR",srcc))) return 0x137;
  if ((srcc==3)&&!(ps_memcasecmp(src,"TL2",srcc))) return 0x138;
  if ((srcc==3)&&!(ps_memcasecmp(src,"TR2",srcc))) return 0x139;
  if ((srcc==6)&&!(ps_memcasecmp(src,"SELECT",srcc))) return 0x13a;
  if ((srcc==5)&&!(ps_memcasecmp(src,"START",srcc))) return 0x13b;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MODE",srcc))) return 0x13c;
  if ((srcc==6)&&!(ps_memcasecmp(src,"THUMBL",srcc))) return 0x13d;
  if ((srcc==6)&&!(ps_memcasecmp(src,"THUMBR",srcc))) return 0x13e;
  if ((srcc==4)&&!(ps_memcasecmp(src,"DIGI",srcc))) return 0x140;
  if ((srcc==8)&&!(ps_memcasecmp(src,"TOOL_PEN",srcc))) return 0x140;
  if ((srcc==11)&&!(ps_memcasecmp(src,"TOOL_RUBBER",srcc))) return 0x141;
  if ((srcc==10)&&!(ps_memcasecmp(src,"TOOL_BRUSH",srcc))) return 0x142;
  if ((srcc==11)&&!(ps_memcasecmp(src,"TOOL_PENCIL",srcc))) return 0x143;
  if ((srcc==13)&&!(ps_memcasecmp(src,"TOOL_AIRBRUSH",srcc))) return 0x144;
  if ((srcc==11)&&!(ps_memcasecmp(src,"TOOL_FINGER",srcc))) return 0x145;
  if ((srcc==10)&&!(ps_memcasecmp(src,"TOOL_MOUSE",srcc))) return 0x146;
  if ((srcc==9)&&!(ps_memcasecmp(src,"TOOL_LENS",srcc))) return 0x147;
  if ((srcc==5)&&!(ps_memcasecmp(src,"TOUCH",srcc))) return 0x14a;
  if ((srcc==6)&&!(ps_memcasecmp(src,"STYLUS",srcc))) return 0x14b;
  if ((srcc==7)&&!(ps_memcasecmp(src,"STYLUS2",srcc))) return 0x14c;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TOOL_DOUBLETAP",srcc))) return 0x14d;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TOOL_TRIPLETAP",srcc))) return 0x14e;
  if ((srcc==5)&&!(ps_memcasecmp(src,"WHEEL",srcc))) return 0x150;
  if ((srcc==9)&&!(ps_memcasecmp(src,"GEAR_DOWN",srcc))) return 0x150;
  if ((srcc==7)&&!(ps_memcasecmp(src,"GEAR_UP",srcc))) return 0x151;
  if ((srcc==7)&&!(ps_memcasecmp(src,"DPAD_UP",srcc))) return 0x220;
  if ((srcc==9)&&!(ps_memcasecmp(src,"DPAD_DOWN",srcc))) return 0x221;
  if ((srcc==9)&&!(ps_memcasecmp(src,"DPAD_LEFT",srcc))) return 0x222;
  if ((srcc==10)&&!(ps_memcasecmp(src,"DPAD_RIGHT",srcc))) return 0x223;
  if ((srcc==13)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY",srcc))) return 0x2c0;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY1",srcc))) return 0x2c0;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY2",srcc))) return 0x2c1;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY3",srcc))) return 0x2c2;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY4",srcc))) return 0x2c3;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY5",srcc))) return 0x2c4;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY6",srcc))) return 0x2c5;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY7",srcc))) return 0x2c6;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY8",srcc))) return 0x2c7;
  if ((srcc==14)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY9",srcc))) return 0x2c8;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY10",srcc))) return 0x2c9;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY11",srcc))) return 0x2ca;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY12",srcc))) return 0x2cb;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY13",srcc))) return 0x2cc;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY14",srcc))) return 0x2cd;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY15",srcc))) return 0x2ce;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY16",srcc))) return 0x2cf;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY17",srcc))) return 0x2d0;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY18",srcc))) return 0x2d1;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY19",srcc))) return 0x2d2;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY20",srcc))) return 0x2d3;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY21",srcc))) return 0x2d4;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY22",srcc))) return 0x2d5;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY23",srcc))) return 0x2d6;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY24",srcc))) return 0x2d7;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY25",srcc))) return 0x2d8;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY26",srcc))) return 0x2d9;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY27",srcc))) return 0x2da;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY28",srcc))) return 0x2db;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY29",srcc))) return 0x2dc;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY30",srcc))) return 0x2dd;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY31",srcc))) return 0x2de;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY32",srcc))) return 0x2df;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY33",srcc))) return 0x2e0;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY34",srcc))) return 0x2e1;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY35",srcc))) return 0x2e2;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY36",srcc))) return 0x2e3;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY37",srcc))) return 0x2e4;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY38",srcc))) return 0x2e5;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY39",srcc))) return 0x2e6;
  if ((srcc==15)&&!(ps_memcasecmp(src,"TRIGGER_HAPPY40",srcc))) return 0x2e7;
  return -1;
}

/* Evaluate ABS event, without prefix.
 */

static int ps_evdev_btnid_ABS_eval(const char *src,int srcc) {
  if ((srcc==1)&&!(ps_memcasecmp(src,"X",srcc))) return 0x00;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Y",srcc))) return 0x01;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Z",srcc))) return 0x02;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RX",srcc))) return 0x03;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RY",srcc))) return 0x04;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RZ",srcc))) return 0x05;
  if ((srcc==8)&&!(ps_memcasecmp(src,"THROTTLE",srcc))) return 0x06;
  if ((srcc==6)&&!(ps_memcasecmp(src,"RUDDER",srcc))) return 0x07;
  if ((srcc==5)&&!(ps_memcasecmp(src,"WHEEL",srcc))) return 0x08;
  if ((srcc==3)&&!(ps_memcasecmp(src,"GAS",srcc))) return 0x09;
  if ((srcc==5)&&!(ps_memcasecmp(src,"BRAKE",srcc))) return 0x0a;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT0X",srcc))) return 0x10;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT0Y",srcc))) return 0x11;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT1X",srcc))) return 0x12;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT1Y",srcc))) return 0x13;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT2X",srcc))) return 0x14;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT2Y",srcc))) return 0x15;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT3X",srcc))) return 0x16;
  if ((srcc==5)&&!(ps_memcasecmp(src,"HAT3Y",srcc))) return 0x17;
  if ((srcc==8)&&!(ps_memcasecmp(src,"PRESSURE",srcc))) return 0x18;
  if ((srcc==8)&&!(ps_memcasecmp(src,"DISTANCE",srcc))) return 0x19;
  if ((srcc==6)&&!(ps_memcasecmp(src,"TILT_X",srcc))) return 0x1a;
  if ((srcc==6)&&!(ps_memcasecmp(src,"TILT_Y",srcc))) return 0x1b;
  if ((srcc==10)&&!(ps_memcasecmp(src,"TOOL_WIDTH",srcc))) return 0x1c;
  if ((srcc==6)&&!(ps_memcasecmp(src,"VOLUME",srcc))) return 0x20;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MISC",srcc))) return 0x28;
  return -1;
}

/* Evaluate REL event, without prefix.
 */

static int ps_evdev_btnid_REL_eval(const char *src,int srcc) {
  if ((srcc==1)&&!(ps_memcasecmp(src,"X",srcc))) return 0x00;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Y",srcc))) return 0x01;
  if ((srcc==1)&&!(ps_memcasecmp(src,"Z",srcc))) return 0x02;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RX",srcc))) return 0x03;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RY",srcc))) return 0x04;
  if ((srcc==2)&&!(ps_memcasecmp(src,"RZ",srcc))) return 0x05;
  if ((srcc==6)&&!(ps_memcasecmp(src,"HWHEEL",srcc))) return 0x06;
  if ((srcc==4)&&!(ps_memcasecmp(src,"DIAL",srcc))) return 0x07;
  if ((srcc==5)&&!(ps_memcasecmp(src,"WHEEL",srcc))) return 0x08;
  if ((srcc==4)&&!(ps_memcasecmp(src,"MISC",srcc))) return 0x09;
  return -1;
}

/* Evaluate button.
 */
 
int ps_evdev_btnid_eval(int *btnid,const char *src,int srcc) {
  if (!btnid||!src) return -1;
  if (srcc<0) { srcc=0; while (src[srcc]) srcc++; }

  int pfxc=0;
  int i=0; for (;i<srcc;i++) {
    if (src[i]=='_') {
      pfxc=i;
      break;
    }
  }

  if ((pfxc==3)&&!ps_memcasecmp(src,"KEY",3)) {
    if ((*btnid=ps_evdev_btnid_KEY_eval(src+4,srcc-4))>=0) { *btnid|=(EV_KEY<<16); return 0; }
  }
  if ((pfxc==3)&&!ps_memcasecmp(src,"BTN",3)) {
    if ((*btnid=ps_evdev_btnid_BTN_eval(src+4,srcc-4))>=0) { *btnid|=(EV_KEY<<16); return 0; }
  }
  if ((pfxc==3)&&!ps_memcasecmp(src,"ABS",3)) {
    if ((*btnid=ps_evdev_btnid_ABS_eval(src+4,srcc-4))>=0) { *btnid|=(EV_ABS<<16); return 0; }
  }
  if ((pfxc==3)&&!ps_memcasecmp(src,"REL",3)) {
    if ((*btnid=ps_evdev_btnid_REL_eval(src+4,srcc-4))>=0) { *btnid|=(EV_REL<<16); return 0; }
  }
  
  return -1;
}

/* Usage for KEY events.
 */

static int ps_evdev_default_usage_for_KEY(int code) {
  switch (code) {
    case                   KEY_ESC: return 0x00070029;
    case                     KEY_1: return 0x0007001e;
    case                     KEY_2: return 0x0007001f;
    case                     KEY_3: return 0x00070020;
    case                     KEY_4: return 0x00070021;
    case                     KEY_5: return 0x00070022;
    case                     KEY_6: return 0x00070023;
    case                     KEY_7: return 0x00070024;
    case                     KEY_8: return 0x00070025;
    case                     KEY_9: return 0x00070026;
    case                     KEY_0: return 0x00070027;
    case                 KEY_MINUS: return 0x0007002d;
    case                 KEY_EQUAL: return 0x0007002e;
    case             KEY_BACKSPACE: return 0x0007002a;
    case                   KEY_TAB: return 0x0007002b;
    case                     KEY_Q: return 0x00070014;
    case                     KEY_W: return 0x0007001a;
    case                     KEY_E: return 0x00070008;
    case                     KEY_R: return 0x00070015;
    case                     KEY_T: return 0x00070017;
    case                     KEY_Y: return 0x0007001c;
    case                     KEY_U: return 0x00070018;
    case                     KEY_I: return 0x0007000c;
    case                     KEY_O: return 0x00070012;
    case                     KEY_P: return 0x00070013;
    case             KEY_LEFTBRACE: return 0x0007002f;
    case            KEY_RIGHTBRACE: return 0x00070030;
    case                 KEY_ENTER: return 0x00070028;
    case              KEY_LEFTCTRL: return 0x000700e0;
    case                     KEY_A: return 0x00070004;
    case                     KEY_S: return 0x00070016;
    case                     KEY_D: return 0x00070007;
    case                     KEY_F: return 0x00070009;
    case                     KEY_G: return 0x0007000a;
    case                     KEY_H: return 0x0007000b;
    case                     KEY_J: return 0x0007000d;
    case                     KEY_K: return 0x0007000e;
    case                     KEY_L: return 0x0007000f;
    case             KEY_SEMICOLON: return 0x00070033;
    case            KEY_APOSTROPHE: return 0x00070034;
    case                 KEY_GRAVE: return 0x00070035;
    case             KEY_LEFTSHIFT: return 0x000700e1;
    case             KEY_BACKSLASH: return 0x00070031;
    case                     KEY_Z: return 0x0007001d;
    case                     KEY_X: return 0x0007001b;
    case                     KEY_C: return 0x00070006;
    case                     KEY_V: return 0x00070019;
    case                     KEY_B: return 0x00070005;
    case                     KEY_N: return 0x00070011;
    case                     KEY_M: return 0x00070010;
    case                 KEY_COMMA: return 0x00070036;
    case                   KEY_DOT: return 0x00070037;
    case                 KEY_SLASH: return 0x00070038;
    case            KEY_RIGHTSHIFT: return 0x000700e5;
    case            KEY_KPASTERISK: return 0x00070055;
    case               KEY_LEFTALT: return 0x000700e2;
    case                 KEY_SPACE: return 0x0007002c;
    case              KEY_CAPSLOCK: return 0x00070039;
    case                    KEY_F1: return 0x0007003a;
    case                    KEY_F2: return 0x0007003b;
    case                    KEY_F3: return 0x0007003c;
    case                    KEY_F4: return 0x0007003d;
    case                    KEY_F5: return 0x0007003e;
    case                    KEY_F6: return 0x0007003f;
    case                    KEY_F7: return 0x00070040;
    case                    KEY_F8: return 0x00070041;
    case                    KEY_F9: return 0x00070042;
    case                   KEY_F10: return 0x00070043;
    case               KEY_NUMLOCK: return 0x00070053;
    case            KEY_SCROLLLOCK: return 0x00070047;
    case                   KEY_KP7: return 0x0007005f;
    case                   KEY_KP8: return 0x00070060;
    case                   KEY_KP9: return 0x00070061;
    case               KEY_KPMINUS: return 0x00070056;
    case                   KEY_KP4: return 0x0007005c;
    case                   KEY_KP5: return 0x0007005d;
    case                   KEY_KP6: return 0x0007005e;
    case                KEY_KPPLUS: return 0x00070057;
    case                   KEY_KP1: return 0x00070059;
    case                   KEY_KP2: return 0x0007005a;
    case                   KEY_KP3: return 0x0007005b;
    case                   KEY_KP0: return 0x00070062;
    case                 KEY_KPDOT: return 0x00070063;
    case                   KEY_F11: return 0x00070044;
    case                   KEY_F12: return 0x00070045;
    case               KEY_KPENTER: return 0x00070058;
    case             KEY_RIGHTCTRL: return 0x000700e4;
    case               KEY_KPSLASH: return 0x00070054;
    case                 KEY_SYSRQ: return 0x0007009a;
    case              KEY_RIGHTALT: return 0x000700e6;
    case                  KEY_HOME: return 0x0007004a;
    case                    KEY_UP: return 0x00070052;
    case                KEY_PAGEUP: return 0x0007004b;
    case                  KEY_LEFT: return 0x00070050;
    case                 KEY_RIGHT: return 0x0007004f;
    case                   KEY_END: return 0x0007004d;
    case                  KEY_DOWN: return 0x00070051;
    case              KEY_PAGEDOWN: return 0x0007004e;
    case                KEY_INSERT: return 0x00070049;
    case                KEY_DELETE: return 0x0007004c;
    case                  KEY_MUTE: return 0x0007007f;
    case            KEY_VOLUMEDOWN: return 0x00070081;
    case              KEY_VOLUMEUP: return 0x00070080;
    case               KEY_KPEQUAL: return 0x00070067;
    case               KEY_KPCOMMA: return 0x00070085;
    case              KEY_LEFTMETA: return 0x000700e3;
    case             KEY_RIGHTMETA: return 0x000700e7;
    case                 KEY_AGAIN: return 0x000700a2;
    case                   KEY_F13: return 0x00070068;
    case                   KEY_F14: return 0x00070069;
    case                   KEY_F15: return 0x0007006a;
    case                   KEY_F16: return 0x0007006b;
    case                   KEY_F17: return 0x0007006c;
    case                   KEY_F18: return 0x0007006d;
    case                   KEY_F19: return 0x0007006e;
    case                   KEY_F20: return 0x0007006f;
    case                   KEY_F21: return 0x00070070;
    case                   KEY_F22: return 0x00070071;
    case                   KEY_F23: return 0x00070072;
    case                   KEY_F24: return 0x00070073;
    case                 KEY_CLEAR: return 0x0007009c;
    case                     BTN_0: return 0x00090001;
    case                     BTN_1: return 0x00090002;
    case                     BTN_2: return 0x00090003;
    case                     BTN_3: return 0x00090004;
    case                     BTN_4: return 0x00090005;
    case                     BTN_5: return 0x00090006;
    case                     BTN_6: return 0x00090007;
    case                     BTN_7: return 0x00090008;
    case                     BTN_8: return 0x00090009;
    case                     BTN_9: return 0x0009000a;
    case                  BTN_LEFT: return 0x00090001;
    case                 BTN_RIGHT: return 0x00090002;
    case                BTN_MIDDLE: return 0x00090003;
    case                  BTN_SIDE: return 0x00090004;
    case                 BTN_EXTRA: return 0x00090005;
    case               BTN_FORWARD: return 0x00090006;
    case                  BTN_BACK: return 0x00090007;
    case                  BTN_TASK: return 0x00090008;
    case               BTN_TRIGGER: return 0x00090010;
    case                 BTN_THUMB: return 0x00090011;
    case                BTN_THUMB2: return 0x00090012;
    case                   BTN_TOP: return 0x00090013;
    case                  BTN_TOP2: return 0x00090014;
    case                BTN_PINKIE: return 0x00090015;
    case                  BTN_BASE: return 0x00090016;
    case                 BTN_BASE2: return 0x00090017;
    case                 BTN_BASE3: return 0x00090018;
    case                 BTN_BASE4: return 0x00090019;
    case                 BTN_BASE5: return 0x0009001a;
    case                 BTN_BASE6: return 0x0009001b;
    case                     BTN_A: return 0x00090001;
    case                     BTN_B: return 0x00090002;
    case                     BTN_C: return 0x00090003;
    case                     BTN_X: return 0x00090004;
    case                     BTN_Y: return 0x00090005;
    case                     BTN_Z: return 0x00090006;
    case                    BTN_TL: return 0x00090007;
    case                    BTN_TR: return 0x00090008;
    case                   BTN_TL2: return 0x00090009;
    case                   BTN_TR2: return 0x0009000a;
    case                BTN_SELECT: return 0x0001003e;
    case                 BTN_START: return 0x0001003d;
    case                  BTN_MODE: return 0x0009000b;
    case                BTN_THUMBL: return 0x0009000c;
    case                BTN_THUMBR: return 0x0009000d;
    case               BTN_DPAD_UP: return 0x00010090;
    case             BTN_DPAD_DOWN: return 0x00010091;
    case             BTN_DPAD_LEFT: return 0x00010093;
    case            BTN_DPAD_RIGHT: return 0x00010092;
  }
  return 0;
}

/* Usage for ABS events.
 */

static int ps_evdev_default_usage_for_ABS(int code) {
  switch (code) {
    case           ABS_X: return 0x00010030;
    case           ABS_Y: return 0x00010031;
    case           ABS_Z: return 0x00010032;
    case          ABS_RX: return 0x00010033;
    case          ABS_RY: return 0x00010034;
    case          ABS_RZ: return 0x00010035;
    case    ABS_THROTTLE: return 0x000200bb;
    case      ABS_RUDDER: return 0x000200ba;
    case       ABS_WHEEL: return 0x000200c8;
    case         ABS_GAS: return 0x000200c4;
    case       ABS_BRAKE: return 0x000200c5;
    case       ABS_HAT0X: return 0x00010030;
    case       ABS_HAT0Y: return 0x00010031;
    case       ABS_HAT1X: return 0x00010030;
    case       ABS_HAT1Y: return 0x00010031;
    case       ABS_HAT2X: return 0x00010030;
    case       ABS_HAT2Y: return 0x00010031;
    case       ABS_HAT3X: return 0x00010030;
    case       ABS_HAT3Y: return 0x00010031;
  }
  return 0;
}

/* Usage for REL events.
 */

static int ps_evdev_default_usage_for_REL(int code) {
  switch (code) {
    case           REL_X: return 0x00010030;
    case           REL_Y: return 0x00010031;
    case           REL_Z: return 0x00010032;
    case          REL_RX: return 0x00010033;
    case          REL_RY: return 0x00010034;
    case          REL_RZ: return 0x00010035;
    case      REL_HWHEEL: return 0x00010038;
    case        REL_DIAL: return 0x00010037;
    case       REL_WHEEL: return 0x00010038;
  }
  return 0;
}

/* Guess USB-HID usage.
 */
 
int ps_evdev_default_usage_for_event(int type,int code) {
  switch (type) {
    case EV_KEY: return ps_evdev_default_usage_for_KEY(code);
    case EV_ABS: return ps_evdev_default_usage_for_ABS(code);
    case EV_REL: return ps_evdev_default_usage_for_REL(code);
  }
  return 0;
}
